# Generated by Django 3.0.8 on 2020-08-02 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancy',
            old_name='specialty',
            new_name='cat',
        ),
    ]
