# Generated by Django 3.0.8 on 2020-08-14 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0003_company_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='owner',
        ),
    ]
